### PR TITLE
GitHub plugin support

### PR DESCRIPTION
**Pull request by jj4th**
Added plugin support and a github plugin

* [ ] Add tests
* [ ] Plugin documentation

### CODE REVIEW

**Comment by jj4th** [comment]
Demo failed:
<hr>
### Test FAILED!! :( ###
Link: http://www.google.com
**Pass:** *1570*  |  **Pend:** *111*  |  **Fail:** *1*

**Comment by jj4th** [comment]
Demo passed:
<hr>
#### Test passed :) ####
Link: http://www.google.com
**Pass:** *1570*  |  **Pend:** *111*

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: http://www.google.com
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Test-9](http://www.google.com#d1501ad5b3f56b10c197b32e1bc8e133bb336cae)

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: http://www.google.com
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Test-9](http://www.google.com#d1501ad5b3f56b10c197b32e1bc8e133bb336cae)

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Test-9](https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html#d1501ad5b3f56b10c197b32e1bc8e133bb336cae)

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Should be Test-9](https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html#bdefb78a0829751a23526c2f95a5bb7ebdba9ee4)

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Should be Test-9](https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html#bdefb78a0829751a23526c2f95a5bb7ebdba9ee4)

**Comment by comeatmebro** [comment]
### Test FAILED!! :(###
Link: https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html
**Pass:** *9*  |  **Pend:** *0*  |  **Fail:** *1*

Failures:
[Suite-5 - Child-5 - Should be Test-9](https://cdn.rawgit.com/jj4th/spectreport/github-plugin/demo/index.html#bdefb78a0829751a23526c2f95a5bb7ebdba9ee4)

**Comment by comeatmebro** [comment]
#### Test passed :) ####
Link: http://www.google.com/HTML_Report
**Pass:** *16*  |  **Pend:** *0*

**Comment by comeatmebro** [comment]
#### Test passed :) ####
Link: http://www.google.com/HTML_Report
**Pass:** *16*  |  **Pend:** *0*

**Comment by comeatmebro** [comment]
#### Test passed :) ####
Link: http://www.google.com/HTML_Report
**Pass:** *16*  |  **Pend:** *0*

**Pull request merged**
